apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Core infra only I manage — storage, networking, monitoring
  sourceRepos:
    - "https://github.com/joex422/homelab-gitops.git"
    - "https://metallb.github.io/metallb"
    - "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://charts.jenkins.io"
    - "https://github.com/kubernetes-sigs/gateway-api.git"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
