apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  description: Everything running on the prod cluster
  sourceRepos:
    - "https://github.com/joex422/homelab-gitops.git"
    - "https://metallb.github.io/metallb"
    - "https://kubernetes-sigs.github.io/headlamp"
    - "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"
    - "https://helm.elastic.co"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"