apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "29"
spec:
  project: prod
  source:
    repoURL: https://github.com/joex422/homelab-gitops.git
    targetRevision: main
    path: apps/prod/infrastructure/homepage
    directory:
      include: "configmap.yaml,deployment.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
