apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "28"
spec:
  project: prod
  source:
    repoURL: https://github.com/joex422/homelab-gitops.git
    targetRevision: main
    path: apps/prod/infrastructure/cloudflared
    directory:
      include: "deployment.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true